language: node_js
node_js: 
  - "node"
install: 
  - npm install
script: 
  - npm test
  - npm run cover
after_success: 
  - npm run coveralls
after_script: 
  - "cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js"
